### PR TITLE
Enhanced Algorithm for Encrypting and Decrypting a Caesar Cipher

### PR DESCRIPTION
**Pull request by VerisimilitudeX**

### CODE REVIEW

**Comment by VerisimilitudeX** [comment]
@Sascha-T @arguiot @arwn could someone please review this PR? Thanks!

**Comment by arguiot** [comment]
Sorry for the delay, since the merge with Cryptool, we don't really maintain repos actively anymore! I think this PR looks good

**Comment by arguiot** [comment]
Is there a way to make it shorter? 800 lines for this cipher seems way too big compared to other languages

**Comment by VerisimilitudeX** [comment]
Hey @arguiot, no worries! Sure thing, I can reduce the number of lines for this cipher. Is there a certain number you want me to target?

**Comment by arguiot** [comment]
It's not necessarily a number of line required but more of an optimization problem. If you can use more of the standard library to just make the cipher works in a minimal way, that would be great!

**Comment by VerisimilitudeX** [comment]
Alright, sounds great! I'll ping you again once I resolve this (ETA 12/31). Sorry for the trouble btw.

**Comment by VerisimilitudeX** [comment]
@lukalafaye awesome thank you!

**Pull request merged**
